// src/lib/db/seedData.ts
import type { LocalBook, LocalLesson } from './db';

export const SEED_BOOK: LocalBook = {
  id: 'tastenzauberei-1',
  title: 'Tastenzauberei Band 1',
  publisher: 'Anikó Drabon / Mitras Music',
  coverImageR2Url: 'https://images.unsplash.com/photo-1520523839898-507127053c17?auto=format&fit=crop&w=400&q=80',
  updatedAt: Date.now()
};

export const SEED_LESSONS: LocalLesson[] = [
  {
    id: 'ch-0',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Schaukeln",
    sequenceIndex: 1,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 0,
    endTime: 68,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-1',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Gespräch in der Höhle",
    sequenceIndex: 2,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 68,
    endTime: 104,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-2',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Gespenster?",
    sequenceIndex: 3,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 104,
    endTime: 150,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-3',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Nach dem Gewitter",
    sequenceIndex: 4,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 150,
    endTime: 172,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-4',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Pitsche - patsch",
    sequenceIndex: 5,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 172,
    endTime: 193,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-5',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Old Mac Donald",
    sequenceIndex: 6,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 193,
    endTime: 214,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-6',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Laterne, laterne",
    sequenceIndex: 7,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 214,
    endTime: 247,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-7',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Jingle Bells",
    sequenceIndex: 8,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 247,
    endTime: 285,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-8',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Morgen kommt der Weihnachtsmann",
    sequenceIndex: 9,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 285,
    endTime: 314,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-9',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Kuckuck, kuckuck",
    sequenceIndex: 10,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 314,
    endTime: 342,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-10',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Noten lesen & Ganztonleiter",
    sequenceIndex: 11,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 342,
    endTime: 395,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-11',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Der Zauberspiegel",
    sequenceIndex: 12,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 395,
    endTime: 424,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-12',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Herr C",
    sequenceIndex: 13,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 424,
    endTime: 457,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-13',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Im Zauberspiegel: Dino und Hase",
    sequenceIndex: 14,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 457,
    endTime: 486,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-14',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Regenwalzer",
    sequenceIndex: 15,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 486,
    endTime: 516,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-15',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Im Zauberspiegel: Elefant und Affe",
    sequenceIndex: 16,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 516,
    endTime: 543,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-16',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Feuer!",
    sequenceIndex: 17,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 543,
    endTime: 580,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-17',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Alle zusammen",
    sequenceIndex: 18,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 580,
    endTime: 611,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-18',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Legato - staccato",
    sequenceIndex: 19,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 611,
    endTime: 659,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-19',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Piratenlied",
    sequenceIndex: 20,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 659,
    endTime: 708,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-20',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Musik in der Nacht",
    sequenceIndex: 21,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 708,
    endTime: 753,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-21',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Im Zauberspiegel: Ferdinand und Geri",
    sequenceIndex: 22,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 753,
    endTime: 785,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-22',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Tanzparty",
    sequenceIndex: 23,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 785,
    endTime: 836,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-23',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Streiterei",
    sequenceIndex: 24,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 836,
    endTime: 870,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-24',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Gradeaus!",
    sequenceIndex: 25,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 870,
    endTime: 928,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-25',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Yankee Doodle",
    sequenceIndex: 26,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 928,
    endTime: 963,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-26',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Froschkonzert",
    sequenceIndex: 27,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 963,
    endTime: 1007,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-27',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Im Zauberspiegel: “Schlüssel-Geri” und “Schlüssel-Ferdinand”",
    sequenceIndex: 28,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1007,
    endTime: 1045,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-28',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Glocken",
    sequenceIndex: 29,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1045,
    endTime: 1093,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-29',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Treppensteigen",
    sequenceIndex: 30,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1093,
    endTime: 1127,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-30',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Joseph Haydn: Thema aus der Paukenschlag-Symphonie",
    sequenceIndex: 31,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1127,
    endTime: 1148,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-31',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Zwei Spechte",
    sequenceIndex: 32,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1148,
    endTime: 1178,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-32',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Happy Birthday",
    sequenceIndex: 33,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1178,
    endTime: 1232,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-33',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Finde die Quinte!",
    sequenceIndex: 34,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1232,
    endTime: 1251,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-34',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Hopplaho!",
    sequenceIndex: 35,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1251,
    endTime: 1289,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-35',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Spiegelbildlich und parallel",
    sequenceIndex: 36,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1289,
    endTime: 1309,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-36',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Fingersport",
    sequenceIndex: 37,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1309,
    endTime: 1355,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-37',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Im Regen",
    sequenceIndex: 38,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1355,
    endTime: 1399,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-38',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Unglaublich",
    sequenceIndex: 39,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1399,
    endTime: 1433,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-39',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Bärentanz",
    sequenceIndex: 40,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1433,
    endTime: 1499,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-40',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Traumlied",
    sequenceIndex: 41,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1499,
    endTime: 1581,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-41',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Im Zirkus",
    sequenceIndex: 42,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1581,
    endTime: 1614,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-42',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Die Versetzungszeichen",
    sequenceIndex: 43,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1614,
    endTime: 1643,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-43',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Der Fisch",
    sequenceIndex: 44,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1643,
    endTime: 1686,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-44',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Der Besen",
    sequenceIndex: 45,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1686,
    endTime: 1721,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-45',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Das Auflösungszeichen",
    sequenceIndex: 46,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1721,
    endTime: 1750,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-46',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Oh, When the Saints…",
    sequenceIndex: 47,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1750,
    endTime: 1786,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-47',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Alle Vögel…",
    sequenceIndex: 48,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1786,
    endTime: 1822,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-48',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Big Ben",
    sequenceIndex: 49,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1822,
    endTime: 1862,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-49',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Die Spieluhr",
    sequenceIndex: 50,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1862,
    endTime: 1900,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-50',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Das Karussell",
    sequenceIndex: 51,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1900,
    endTime: 1939,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-51',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Die Lokomotive",
    sequenceIndex: 52,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1939,
    endTime: 1990,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-52',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Hokuspo-Blues",
    sequenceIndex: 53,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 1990,
    endTime: 2032,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  },
  {
    id: 'ch-53',
    bookId: 'tastenzauberei-1',
    providerName: 'Anikó Drabon (Original)',
    title: "Beethoven: An die Freude",
    sequenceIndex: 54,
    youtubeVideoId: 'lguxe5bEqXo',
    startTime: 2032,
    endTime: 2152,
    checkpoints: ['Focus on the rhythm and dynamics'],
    isCompleted: false
  }
];
